# Generated by Django 5.1.1 on 2024-10-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product',
            new_name='transport',
        ),
    ]
