# Generated by Django 5.1.1 on 2024-10-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_product_basket_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='transport',
            new_name='product',
        ),
    ]
