# Generated by Django 5.1.1 on 2024-10-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_transport_basket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
